// GENERATED by worker/build.mjs from parse.js + worker.js. Do not edit by hand.
// Paste this whole file into the Cloudflare dashboard editor (see worker/README.md).

// ===== parse.js =====
// RSS 2.0 / RSS 1.0 (RDF) / Atom → Bonsai items. Pure string work: Cloudflare
// Workers have no DOMParser, and this file is also imported by the Node tests.

const NAMED = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: '\u00a0',
  mdash: '—', ndash: '–', hellip: '…', rsquo: '’', lsquo: '‘', rdquo: '”', ldquo: '“',
  middot: '·', copy: '©', reg: '®', trade: '™', eacute: 'é', egrave: 'è', aacute: 'á',
  iacute: 'í', oacute: 'ó', uacute: 'ú', ntilde: 'ñ', uuml: 'ü', ouml: 'ö', auml: 'ä', ccedil: 'ç',
};

function decodeEntities(s) {
  if (!s || s.indexOf('&') < 0) return s || '';
  return s.replace(/&(#x[0-9a-f]+|#[0-9]+|[a-z][a-z0-9]*);/gi, (m, e) => {
    if (e[0] === '#') {
      const n = e[1] === 'x' || e[1] === 'X' ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
      return Number.isFinite(n) && n > 0 && n < 0x110000 ? String.fromCodePoint(n) : m;
    }
    const v = NAMED[e.toLowerCase()];
    return v === undefined ? m : v;
  });
}

// Inner text of a tag's content: CDATA is taken raw, anything else is entity-decoded once.
function unwrap(inner) {
  const t = inner.trim();
  const cdata = /^<!\[CDATA\[([\s\S]*?)\]\]>$/.exec(t);
  if (cdata) return cdata[1];
  // mixed CDATA sections inside a value
  if (t.indexOf('<![CDATA[') >= 0) return t.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1');
  return decodeEntities(t);
}

const esc = (name) => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const TAG_RE = new Map();
function tagRe(name) {
  let re = TAG_RE.get(name);
  if (!re) {
    re = new RegExp('<' + esc(name) + '(?:\\s[^>]*)?>([\\s\\S]*?)</' + esc(name) + '\\s*>', 'i');
    TAG_RE.set(name, re);
  }
  return re;
}

// First matching element's inner content, trying names in order (e.g. 'content:encoded').
function tag(block, names) {
  for (const name of names) {
    const m = tagRe(name).exec(block);
    if (m && m[1].trim()) return unwrap(m[1]);
  }
  return '';
}

// Attribute of the first self-closing or open tag with that name.
function attr(block, name, attrName, where) {
  const re = new RegExp('<' + esc(name) + '\\b([^>]*)>', 'gi');
  let m;
  while ((m = re.exec(block))) {
    const attrs = m[1];
    if (where && !where(attrs)) continue;
    const a = new RegExp('\\b' + esc(attrName) + '\\s*=\\s*("([^"]*)"|\'([^\']*)\')', 'i').exec(attrs);
    if (a) return decodeEntities(a[2] ?? a[3]);
  }
  return '';
}

function stripTags(html) {
  return decodeEntities(
    String(html || '')
      .replace(/<(script|style|iframe|noscript)\b[\s\S]*?<\/\1\s*>/gi, ' ')
      .replace(/<\/?(br|p|div|li|ul|ol|h[1-6]|blockquote|section|article|figure|figcaption|table|tr|td|th|hr)\b[^>]*>/gi, ' ')
      .replace(/<[^>]+>/g, ''),
  ).replace(/\s+/g, ' ').trim();
}

function makeExcerpt(text, max = 280) {
  const t = (text || '').trim();
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  const at = cut.lastIndexOf(' ');
  return (at > max * 0.6 ? cut.slice(0, at) : cut).replace(/[\s,;:.–—-]+$/, '') + '…';
}

// Short stable id (FNV-1a, base36) — the same item keeps the same id across refreshes.
function hashId(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(36);
}

function toIso(s) {
  if (!s) return null;
  const t = Date.parse(s.trim());
  return Number.isFinite(t) ? new Date(t).toISOString() : null;
}

function isHttp(u) {
  return /^https?:\/\//i.test(u || '');
}

const MAX_HTML = 80_000; // bigger bodies are dropped (the item view links out instead)

/**
 * @param {string} xml  the feed document
 * @param {{id:string,name:string,topic:string,kind:string}} source
 * @returns {Array<object>} items, newest first
 */
function parseFeed(xml, source, limit = 50) {
  const doc = String(xml || '');
  const isAtom = /<feed\b[^>]*>/i.test(doc) && !/<rss\b/i.test(doc);
  const blockRe = isAtom ? /<entry\b[\s\S]*?<\/entry\s*>/gi : /<item\b[\s\S]*?<\/item\s*>/gi;

  const items = [];
  let bm;
  while ((bm = blockRe.exec(doc)) && items.length < limit) {
    // Pull the (large) body out first so the other lookups scan a small block.
    let b = bm[0];
    let full = '';
    for (const name of ['content:encoded', 'content']) {
      const m = tagRe(name).exec(b);
      if (m && m[1].trim()) { full = unwrap(m[1]); b = b.slice(0, m.index) + b.slice(m.index + m[0].length); break; }
    }
    const title = stripTags(tag(b, ['title']));

    let link = '';
    if (isAtom) {
      link = attr(b, 'link', 'href', (a) => !/\brel\s*=/.test(a) || /\brel\s*=\s*["']alternate["']/i.test(a));
    } else {
      link = stripTags(tag(b, ['link']));
      if (!isHttp(link)) {
        const guid = stripTags(tag(b, ['guid']));
        if (isHttp(guid)) link = guid;
      }
      if (!isHttp(link)) link = attr(b, 'item', 'rdf:about');
    }
    if (!isHttp(link)) link = '';

    const summary = tag(b, ['description', 'summary', 'itunes:summary', 'media:description']);
    let html = full || summary;
    const excerpt = makeExcerpt(stripTags(summary || full));
    if (html.length > MAX_HTML) html = '';

    const audioUrl = attr(b, 'enclosure', 'url', (a) => /type\s*=\s*["']audio\//i.test(a))
      || attr(b, 'media:content', 'url', (a) => /type\s*=\s*["']audio\//i.test(a));

    const image = attr(b, 'media:thumbnail', 'url')
      || attr(b, 'media:content', 'url', (a) => /medium\s*=\s*["']image["']|type\s*=\s*["']image\//i.test(a))
      || attr(b, 'enclosure', 'url', (a) => /type\s*=\s*["']image\//i.test(a))
      || attr(b, 'itunes:image', 'href')
      || attr(html.slice(0, 20_000), 'img', 'src');

    const published = toIso(tag(b, ['pubDate', 'published', 'dc:date', 'updated', 'prism:publicationDate']));
    const videoId = stripTags(tag(b, ['yt:videoId'])); // YouTube channel feeds
    const guid = stripTags(tag(b, isAtom ? ['id'] : ['guid'])) || link || title;
    if (!title && !excerpt) continue;

    items.push({
      id: hashId(source.id + '|' + guid),
      sourceId: source.id,
      sourceName: source.name,
      topic: source.topic,
      kind: videoId ? 'video' : audioUrl ? 'audio' : source.kind || 'article',
      title: title || excerpt.slice(0, 80),
      url: link,
      published,
      excerpt,
      html: html.trim(),
      audioUrl: isHttp(audioUrl) ? audioUrl : '',
      image: isHttp(image) ? image : '',
      ...(videoId && /^[\w-]{11}$/.test(videoId) ? { videoId, short: /\/shorts\//.test(link) } : {}),
    });
  }

  items.sort((a, b) => (b.published || '').localeCompare(a.published || ''));
  return items;
}

// Paywalled posts ("for paid subscribers", "upgrade to read the rest"…). Used only for
// sources marked `hideLocked`, so a newsletter's own "go premium" plug in a free post
// doesn't hide it: the phrases have to be about *this* post being locked.
const LOCKED = [
  /\b(this|the rest of this|the full) (post|issue|edition|article|story|piece|newsletter)( is| are)? (only )?(for|available (only )?to|reserved for|exclusive to) (paid|paying|premium)/i,
  /\b(subscribe|upgrade|join|become a (paid|paying|premium) (member|subscriber))\b[^.!?]{0,60}\b(to (read|continue reading|keep reading|unlock|access) (the rest|this|the full|more of this)|to read on)\b/i,
  /\b(paid|paying|premium) (subscribers|members) only\b/i,
  /\b(want|ready) to keep reading\?/i,
  /\bunlock (this|the full) (post|issue|article)\b/i,
];

function isLocked(item) {
  // Paywall notices sit at the start or the end of a post; look only there.
  const html = item.html || '';
  const ends = html.length > 8000 ? html.slice(0, 3000) + ' ' + html.slice(-5000) : html;
  const text = stripTags(ends) + ' ' + (item.excerpt || '') + ' ' + (item.title || '');
  return LOCKED.some((re) => re.test(text));
}

// ===== worker.js =====
// bonsai-feeds — Cloudflare Worker
// Keeps one small KV entry per source. Every 5 minutes (cron) it refreshes the sources that are
// due (see MAX_EVERY below), a few at a time within a byte budget so each run stays inside the free
// plan's CPU limit (a large feed takes a few ms to parse).
// GET /feed stitches the stored entries together as text, without re-parsing them.
// Holds no personal keys: it only reads public feeds.


const PER_SOURCE = 12;               // newest items kept per source
const FETCH_TIMEOUT = 15_000;
const REFRESH_GAP = 60_000;          // POST /refresh runs at most once a minute
const MAX_AGE = 2 * 3600_000;        // a source is due for a refresh after 2 hours
const RUN_BYTES = 300_000;           // feed text parsed per run: keeps CPU well inside the free limit
const RUN_MAX = 6;                   // and at most this many sources per run
// Video lengths aren't in YouTube's feeds. The app asks GET /length?v=ID for the videos it shows
// and keeps the answers on the phone, so this costs no KV writes. Reading stops once the length shows.
const LEN_BYTES = 2_000_000;
const BROWSER_UA = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1';
// KV writes (the free plan allows 1,000 a day) come from saving sources. A source is checked every
// 2 h while it has news; each check that finds nothing new doubles its wait, up to 12 h. A topic or
// source in sources.json can ask for a longer minimum ("every": hours): News only feeds the daily
// brief, so it's checked every 6 h. About 200 writes a day for ~60 sources, not 600+.
const MAX_EVERY = 12 * 3600_000;
// Defaults, so the worker runs with only the FEEDS binding set. Override in the worker's variables.
const SOURCES_URL = 'https://atonioguy.github.io/bonsai/sources.json';
const ALLOW_ORIGIN = 'https://atonioguy.github.io';

export default {
  async fetch(req, env, ctx) {
    const url = new URL(req.url);
    const cors = {
      'Access-Control-Allow-Origin': env.ALLOW_ORIGIN || ALLOW_ORIGIN,
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'content-type',
      'Vary': 'Origin',
    };
    if (req.method === 'OPTIONS') return new Response(null, { headers: cors });

    try {
      if (url.pathname === '/feed' && req.method === 'GET') {
        const sources = await loadSources(env);
        let body = await feedBody(env, sources);
        if (!body) { // first visit ever: fetch what fits now so the feed isn't empty
          await refreshDue(env, sources);
          body = (await feedBody(env, sources)) || '{"sources":[]}';
        }
        return new Response(body, { headers: { ...cors, 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' } });
      }
      // Refresh what's due now (for when the schedule isn't running). Writes nothing of its own:
      // skipped if anything was saved in the last minute.
      if (url.pathname === '/refresh' && req.method === 'POST') {
        const meta = await storedMeta(env);
        const newest = Math.max(0, ...[...meta.values()].map((m) => m.fetchedAt || 0));
        if (Date.now() - newest < REFRESH_GAP) return json({ ok: true, skipped: true }, 200, cors);
        const done = await refreshDue(env, await loadSources(env), { meta });
        return json({ ok: true, refreshed: done }, 200, cors);
      }
      // Relay for Europe PMC (full text of open-access papers), in case the browser can't reach it
      // directly. Only its search and full-text XML paths are allowed, so this isn't an open proxy.
      if (url.pathname === '/epmc' && req.method === 'GET') {
        const path = url.searchParams.get('path') || '';
        if (!/^(search\?[^#]*|PMC\d{4,10}\/fullTextXML)$/.test(path)) return json({ error: 'not allowed' }, 400, cors);
        const r = await fetch('https://www.ebi.ac.uk/europepmc/webservices/rest/' + path, { cf: { cacheTtl: 86400 } });
        return new Response(r.body, { status: r.status, headers: { ...cors, 'content-type': r.headers.get('content-type') || 'text/plain' } });
      }
      // A video's length in seconds (0 if YouTube didn't say). ?debug=1 shows what each try found.
      if (url.pathname === '/length' && req.method === 'GET') {
        const v = url.searchParams.get('v') || '';
        if (!/^[\w-]{11}$/.test(v)) return json({ error: 'bad video id' }, 400, cors);
        const found = await videoLength(v);
        return json(url.searchParams.has('debug') ? found : { v, seconds: found.seconds }, 200, cors);
      }
      // How the feed is doing: sources loaded, and when the newest/oldest refresh happened.
      if (url.pathname === '/' || url.pathname === '/health') {
        const sources = await loadSources(env);
        const meta = await storedMeta(env);
        const m = sources.map((x) => meta.get(x.id) || {});
        const loaded = m.map((x) => x.fetchedAt || 0).filter(Boolean);
        return json({
          ok: true, name: 'bonsai-feeds', sources: sources.length, loaded: loaded.length,
          newest: loaded.length ? new Date(Math.max(...loaded)).toISOString() : null,
          overdue: m.filter((x, i) => Date.now() - (x.fetchedAt || 0) >= everyOf(x, sources[i]) + 30 * 60_000).length,
          failing: m.filter((x) => x.ok === false).length,
          writesPerDay: Math.round(m.reduce((n, x, i) => n + 86_400_000 / everyOf(x, sources[i]), 0)), // about, at the current waits
        }, 200, cors);
      }
      return json({ error: 'not found' }, 404, cors);
    } catch (e) {
      return json({ error: String(e && e.message || e) }, 500, cors);
    }
  },

  async scheduled(event, env, ctx) {
    ctx.waitUntil(loadSources(env).then((sources) => refreshDue(env, sources)));
  },
};

async function loadSources(env) {
  const res = await fetch(env.SOURCES_URL || SOURCES_URL, { cf: { cacheTtl: 300 } });
  if (!res.ok) throw new Error('sources.json: HTTP ' + res.status);
  const cfg = await res.json();
  const topicEvery = new Map((cfg.topics || []).map((t) => [t.id, Number(t.every) || 0]));
  return (cfg.sources || []).filter((s) => s.feed)
    .map((s) => ({ ...s, minEvery: (Number(s.every) || topicEvery.get(s.topic) || 0) * 3600_000 }));
}

// The stored entries stitched together as text (no JSON.parse of the big item lists).
async function feedBody(env, sources) {
  const entries = await Promise.all(sources.map((s) => env.FEEDS.getWithMetadata('src:' + s.id)));
  const parts = [];
  entries.forEach((e, i) => {
    if (!e.value) return;
    parts.push('{"id":' + JSON.stringify(sources[i].id) + ',"meta":' + JSON.stringify(e.metadata || {}) + ',"items":' + e.value + '}');
  });
  if (!parts.length) return '';
  return '{"updatedAt":' + JSON.stringify(new Date().toISOString()) + ',"sources":[' + parts.join(',') + ']}';
}

// Each source's saved state (fetchedAt, ok, every, top…) from one KV list.
async function storedMeta(env) {
  const listed = await env.FEEDS.list({ prefix: 'src:' });
  return new Map(listed.keys.map((k) => [k.name.slice(4), k.metadata || {}]));
}

// A source's wait before its next check: its adaptive wait (2–12 h), never under its own minimum.
const everyOf = (m, s) => Math.max((s && s.minEvery) || 0, Math.min(MAX_EVERY, Math.max(MAX_AGE, (m && m.every) || MAX_AGE)));

// Refresh every source that's due (never fetched, or its wait is over), stalest first, until the
// run's byte budget is used. A new install fills in minutes; after that most runs do one or none.
async function refreshDue(env, sources, { meta = null } = {}) {
  if (!sources.length) return [];
  meta = meta || await storedMeta(env);
  const at = (x) => (meta.get(x.id) || {}).fetchedAt || 0;
  const now = Date.now();
  const due = sources.filter((x) => now - at(x) >= everyOf(meta.get(x.id), x)).sort((a, b) => at(a) - at(b));
  const done = [];
  let bytes = 0;
  for (const x of due.slice(0, RUN_MAX)) {
    try {
      bytes += await refreshOne(env, x, meta.get(x.id));
    } catch {
      break; // most likely the daily KV limit: stop here, the next run tries again
    }
    done.push(x.id);
    if (bytes >= RUN_BYTES) break;
  }
  return done;
}

// A video's length: from its watch page (read in pieces, stopping as soon as the length shows up),
// else from YouTube's player API. Each try leaves a note, for /length?debug=1.
async function videoLength(id) {
  const out = { v: id, seconds: 0, tried: [] };
  for (const how of [fromWatchPage, fromPlayerApi]) {
    try {
      const r = await how(id);
      out.tried.push(r.note);
      if (r.seconds) { out.seconds = r.seconds; break; }
    } catch (e) {
      out.tried.push(how.name + ': ' + String(e && e.message || e).slice(0, 120));
    }
  }
  return out;
}

async function fromWatchPage(id) {
  const r = await fetch('https://www.youtube.com/watch?v=' + encodeURIComponent(id) + '&hl=en', {
    headers: { 'user-agent': BROWSER_UA, 'accept-language': 'en-US,en;q=0.8', cookie: 'CONSENT=YES+1; SOCS=CAI' },
    signal: AbortSignal.timeout(FETCH_TIMEOUT),
  });
  const where = /consent\./.test(r.url || '') ? ' (consent page)' : '';
  if (!r.ok || !r.body) return { seconds: 0, note: 'watch page: HTTP ' + r.status + where };
  const reader = r.body.getReader();
  const dec = new TextDecoder();
  let tail = '', bytes = 0, seconds = 0, bot = false;
  while (bytes < LEN_BYTES) {
    const { value, done } = await reader.read();
    if (done) break;
    bytes += value.length;
    const text = tail + dec.decode(value, { stream: true });
    seconds = lengthIn(text);
    if (seconds) break;
    if (/not a bot/i.test(text)) bot = true;
    tail = text.slice(-120);
  }
  reader.cancel().catch(() => {});
  return { seconds, note: `watch page: ${Math.round(bytes / 1024)} KB, ${seconds ? 'found' : 'no length'}${bot ? ' (bot check)' : ''}${where}` };
}

async function fromPlayerApi(id) {
  const r = await fetch('https://www.youtube.com/youtubei/v1/player?prettyPrint=false', {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'user-agent': BROWSER_UA, cookie: 'CONSENT=YES+1; SOCS=CAI' },
    body: JSON.stringify({ videoId: id, context: { client: { clientName: 'WEB', clientVersion: '2.20250901.00.00', hl: 'en' } } }),
    signal: AbortSignal.timeout(FETCH_TIMEOUT),
  });
  const text = r.ok ? await r.text() : '';
  const seconds = lengthIn(text);
  const status = (/"playabilityStatus":\{"status":"(\w+)"/.exec(text) || [])[1] || '';
  return { seconds, note: `player API: HTTP ${r.status}${status ? ', ' + status : ''}, ${seconds ? 'found' : 'no length'}` };
}

function lengthIn(text) {
  const s = /"lengthSeconds":"(\d+)"/.exec(text);
  if (s) return Number(s[1]);
  const iso = /itemprop="duration" content="PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?"/.exec(text);
  if (iso && (iso[1] || iso[2] || iso[3])) return (Number(iso[1] || 0) * 3600) + (Number(iso[2] || 0) * 60) + Number(iso[3] || 0);
  const ms = /"approxDurationMs":"(\d+)"/.exec(text);
  return ms ? Math.round(Number(ms[1]) / 1000) : 0;
}

// `old` is the source's saved metadata. Nothing new since last time (same newest item) doubles its
// wait; something new brings it back to every 2 h. A failing source waits longer too.
async function refreshOne(env, s, old = {}) {
  const key = 'src:' + s.id;
  const longer = Math.min(MAX_EVERY, everyOf(old) * 2); // the adaptive part; a source's minimum applies on top
  let got;
  try {
    got = await fetchOne(s, env);
  } catch (e) {
    // Keep the last good items; just record the failure.
    const prev = await env.FEEDS.getWithMetadata(key);
    await env.FEEDS.put(key, prev.value || '[]', {
      metadata: { ...(prev.metadata || {}), fetchedAt: Date.now(), ok: false, every: longer, error: String(e && e.message || e).slice(0, 160) },
    });
    return 0;
  }
  const open = s.hideLocked ? got.items.filter((it) => !isLocked(it)) : got.items;
  const kept = open.slice(0, PER_SOURCE);
  const top = kept.length ? kept[0].id : '';
  const same = old.ok === true && old.top === top;
  await env.FEEDS.put(key, JSON.stringify(kept), {
    metadata: { fetchedAt: Date.now(), ok: true, count: kept.length, hidden: got.items.length - open.length, top, every: same ? longer : MAX_AGE },
  });
  return got.bytes;
}

// "youtube:@handle" → that channel's video feed. The channel id is looked up once and kept.
async function feedUrl(source, env) {
  const m = /^youtube:(.+)$/.exec(source.feed || '');
  if (!m) return source.feed;
  let id = m[1];
  if (!/^UC[\w-]{22}$/.test(id)) {
    const key = 'yt:' + id.toLowerCase();
    id = await env.FEEDS.get(key);
    if (!id) {
      const page = await fetch('https://www.youtube.com/' + m[1].replace(/^@?/, '@'), {
        headers: { 'accept-language': 'en-US,en;q=0.8', 'user-agent': 'Mozilla/5.0 (compatible; BonsaiFeeds/0.1)' },
        signal: AbortSignal.timeout(FETCH_TIMEOUT),
      });
      if (!page.ok) throw new Error('YouTube channel page: HTTP ' + page.status);
      const html = await page.text();
      id = (/<link rel="canonical" href="https:\/\/www\.youtube\.com\/channel\/(UC[\w-]{22})"/.exec(html)
        || /"externalId":"(UC[\w-]{22})"/.exec(html) || [])[1];
      if (!id) throw new Error('YouTube channel not found: ' + m[1]);
      await env.FEEDS.put(key, id);
    }
  }
  return 'https://www.youtube.com/feeds/videos.xml?channel_id=' + id;
}

async function fetchOne(source, env) {
  const r = await fetch(await feedUrl(source, env), {
    headers: {
      'user-agent': 'BonsaiFeeds/0.1 (personal feed reader; +https://github.com/atonioguy/bonsai)',
      'accept': 'application/rss+xml, application/atom+xml, application/xml;q=0.9, text/xml;q=0.9, */*;q=0.5',
    },
    signal: AbortSignal.timeout(FETCH_TIMEOUT),
    cf: { cacheTtl: 900 },
  });
  if (!r.ok) throw new Error('HTTP ' + r.status);
  const xml = await r.text();
  // Parse a few spare items so hidden (locked) posts can be replaced.
  const items = parseFeed(xml, source, source.hideLocked ? PER_SOURCE * 2 : PER_SOURCE);
  if (!items.length && !/<(rss|feed|rdf:RDF)\b/i.test(xml)) throw new Error('not a feed');
  return { items, bytes: xml.length };
}

function json(obj, status, headers) {
  return new Response(JSON.stringify(obj), { status, headers: { ...headers, 'content-type': 'application/json; charset=utf-8' } });
}
