// GENERATED by worker/build.mjs from parse.js + worker.js. Do not edit by hand.
// Paste this whole file into the Cloudflare dashboard editor (see worker/README.md).

// ===== parse.js =====
// RSS 2.0 / RSS 1.0 (RDF) / Atom → Bonsai items. Pure string work: Cloudflare
// Workers have no DOMParser, and this file is also imported by the Node tests.

const NAMED = {
  amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: '\u00a0',
  mdash: '—', ndash: '–', hellip: '…', rsquo: '’', lsquo: '‘', rdquo: '”', ldquo: '“',
  middot: '·', copy: '©', reg: '®', trade: '™', eacute: 'é', egrave: 'è', aacute: 'á',
  iacute: 'í', oacute: 'ó', uacute: 'ú', ntilde: 'ñ', uuml: 'ü', ouml: 'ö', auml: 'ä', ccedil: 'ç',
};

function decodeEntities(s) {
  if (!s || s.indexOf('&') < 0) return s || '';
  return s.replace(/&(#x[0-9a-f]+|#[0-9]+|[a-z][a-z0-9]*);/gi, (m, e) => {
    if (e[0] === '#') {
      const n = e[1] === 'x' || e[1] === 'X' ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
      return Number.isFinite(n) && n > 0 && n < 0x110000 ? String.fromCodePoint(n) : m;
    }
    const v = NAMED[e.toLowerCase()];
    return v === undefined ? m : v;
  });
}

// Inner text of a tag's content: CDATA is taken raw, anything else is entity-decoded once.
function unwrap(inner) {
  const t = inner.trim();
  const cdata = /^<!\[CDATA\[([\s\S]*?)\]\]>$/.exec(t);
  if (cdata) return cdata[1];
  // mixed CDATA sections inside a value
  if (t.indexOf('<![CDATA[') >= 0) return t.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1');
  return decodeEntities(t);
}

const esc = (name) => name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

const TAG_RE = new Map();
function tagRe(name) {
  let re = TAG_RE.get(name);
  if (!re) {
    re = new RegExp('<' + esc(name) + '(?:\\s[^>]*)?>([\\s\\S]*?)</' + esc(name) + '\\s*>', 'i');
    TAG_RE.set(name, re);
  }
  return re;
}

// First matching element's inner content, trying names in order (e.g. 'content:encoded').
function tag(block, names) {
  for (const name of names) {
    const m = tagRe(name).exec(block);
    if (m && m[1].trim()) return unwrap(m[1]);
  }
  return '';
}

// Attribute of the first self-closing or open tag with that name.
function attr(block, name, attrName, where) {
  const re = new RegExp('<' + esc(name) + '\\b([^>]*)>', 'gi');
  let m;
  while ((m = re.exec(block))) {
    const attrs = m[1];
    if (where && !where(attrs)) continue;
    const a = new RegExp('\\b' + esc(attrName) + '\\s*=\\s*("([^"]*)"|\'([^\']*)\')', 'i').exec(attrs);
    if (a) return decodeEntities(a[2] ?? a[3]);
  }
  return '';
}

function stripTags(html) {
  return decodeEntities(
    String(html || '')
      .replace(/<(script|style|iframe|noscript)\b[\s\S]*?<\/\1\s*>/gi, ' ')
      .replace(/<\/?(br|p|div|li|ul|ol|h[1-6]|blockquote|section|article|figure|figcaption|table|tr|td|th|hr)\b[^>]*>/gi, ' ')
      .replace(/<[^>]+>/g, ''),
  ).replace(/\s+/g, ' ').trim();
}

function makeExcerpt(text, max = 280) {
  const t = (text || '').trim();
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  const at = cut.lastIndexOf(' ');
  return (at > max * 0.6 ? cut.slice(0, at) : cut).replace(/[\s,;:.–—-]+$/, '') + '…';
}

// Short stable id (FNV-1a, base36) — the same item keeps the same id across refreshes.
function hashId(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(36);
}

function toIso(s) {
  if (!s) return null;
  const t = Date.parse(s.trim());
  return Number.isFinite(t) ? new Date(t).toISOString() : null;
}

function isHttp(u) {
  return /^https?:\/\//i.test(u || '');
}

const MAX_HTML = 80_000; // bigger bodies are dropped (the item view links out instead)

/**
 * @param {string} xml  the feed document
 * @param {{id:string,name:string,topic:string,kind:string}} source
 * @returns {Array<object>} items, newest first
 */
function parseFeed(xml, source, limit = 50) {
  const doc = String(xml || '');
  const isAtom = /<feed\b[^>]*>/i.test(doc) && !/<rss\b/i.test(doc);
  const blockRe = isAtom ? /<entry\b[\s\S]*?<\/entry\s*>/gi : /<item\b[\s\S]*?<\/item\s*>/gi;

  const items = [];
  let bm;
  while ((bm = blockRe.exec(doc)) && items.length < limit) {
    // Pull the (large) body out first so the other lookups scan a small block.
    let b = bm[0];
    let full = '';
    for (const name of ['content:encoded', 'content']) {
      const m = tagRe(name).exec(b);
      if (m && m[1].trim()) { full = unwrap(m[1]); b = b.slice(0, m.index) + b.slice(m.index + m[0].length); break; }
    }
    const title = stripTags(tag(b, ['title']));

    let link = '';
    if (isAtom) {
      link = attr(b, 'link', 'href', (a) => !/\brel\s*=/.test(a) || /\brel\s*=\s*["']alternate["']/i.test(a));
    } else {
      link = stripTags(tag(b, ['link']));
      if (!isHttp(link)) {
        const guid = stripTags(tag(b, ['guid']));
        if (isHttp(guid)) link = guid;
      }
      if (!isHttp(link)) link = attr(b, 'item', 'rdf:about');
    }
    if (!isHttp(link)) link = '';

    const summary = tag(b, ['description', 'summary', 'itunes:summary', 'media:description']);
    let html = full || summary;
    const excerpt = makeExcerpt(stripTags(summary || full));
    if (html.length > MAX_HTML) html = '';

    const audioUrl = attr(b, 'enclosure', 'url', (a) => /type\s*=\s*["']audio\//i.test(a))
      || attr(b, 'media:content', 'url', (a) => /type\s*=\s*["']audio\//i.test(a));

    const image = attr(b, 'media:thumbnail', 'url')
      || attr(b, 'media:content', 'url', (a) => /medium\s*=\s*["']image["']|type\s*=\s*["']image\//i.test(a))
      || attr(b, 'enclosure', 'url', (a) => /type\s*=\s*["']image\//i.test(a))
      || attr(b, 'itunes:image', 'href')
      || attr(html.slice(0, 20_000), 'img', 'src');

    const published = toIso(tag(b, ['pubDate', 'published', 'dc:date', 'updated', 'prism:publicationDate']));
    const guid = stripTags(tag(b, isAtom ? ['id'] : ['guid'])) || link || title;
    if (!title && !excerpt) continue;

    items.push({
      id: hashId(source.id + '|' + guid),
      sourceId: source.id,
      sourceName: source.name,
      topic: source.topic,
      kind: audioUrl ? 'audio' : source.kind || 'article',
      title: title || excerpt.slice(0, 80),
      url: link,
      published,
      excerpt,
      html: html.trim(),
      audioUrl: isHttp(audioUrl) ? audioUrl : '',
      image: isHttp(image) ? image : '',
    });
  }

  items.sort((a, b) => (b.published || '').localeCompare(a.published || ''));
  return items;
}

// Paywalled posts ("for paid subscribers", "upgrade to read the rest"…). Used only for
// sources marked `hideLocked`, so a newsletter's own "go premium" plug in a free post
// doesn't hide it: the phrases have to be about *this* post being locked.
const LOCKED = [
  /\b(this|the rest of this|the full) (post|issue|edition|article|story|piece|newsletter)( is| are)? (only )?(for|available (only )?to|reserved for|exclusive to) (paid|paying|premium)/i,
  /\b(subscribe|upgrade|join|become a (paid|paying|premium) (member|subscriber))\b[^.!?]{0,60}\b(to (read|continue reading|keep reading|unlock|access) (the rest|this|the full|more of this)|to read on)\b/i,
  /\b(paid|paying|premium) (subscribers|members) only\b/i,
  /\b(want|ready) to keep reading\?/i,
  /\bunlock (this|the full) (post|issue|article)\b/i,
];

function isLocked(item) {
  // Paywall notices sit at the start or the end of a post; look only there.
  const html = item.html || '';
  const ends = html.length > 8000 ? html.slice(0, 3000) + ' ' + html.slice(-5000) : html;
  const text = stripTags(ends) + ' ' + (item.excerpt || '') + ' ' + (item.title || '');
  return LOCKED.some((re) => re.test(text));
}

// ===== worker.js =====
// bonsai-feeds — Cloudflare Worker
// Keeps one small KV entry per source. Every 5 minutes (cron) it refreshes the one source
// that's been waiting longest, so each run stays well inside the free plan's CPU limit
// (a large feed takes a few ms to parse). With ~22 sources, each refreshes about every 2 h.
// GET /feed stitches the stored entries together as text, without re-parsing them.
// Holds no personal keys: it only reads public feeds.


const PER_SOURCE = 12;               // newest items kept per source
const FETCH_TIMEOUT = 15_000;
const REFRESH_GAP = 60_000;          // POST /refresh does at most one source a minute
// Defaults, so the worker runs with only the FEEDS binding set. Override in the worker's variables.
const SOURCES_URL = 'https://atonioguy.github.io/bonsai/sources.json';
const ALLOW_ORIGIN = 'https://atonioguy.github.io';

export default {
  async fetch(req, env, ctx) {
    const url = new URL(req.url);
    const cors = {
      'Access-Control-Allow-Origin': env.ALLOW_ORIGIN || ALLOW_ORIGIN,
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'content-type',
      'Vary': 'Origin',
    };
    if (req.method === 'OPTIONS') return new Response(null, { headers: cors });

    try {
      if (url.pathname === '/feed' && req.method === 'GET') {
        const sources = await loadSources(env);
        let body = await feedBody(env, sources);
        if (!body) { // first visit ever: fetch one source now so the feed isn't empty
          await refreshNext(env, sources);
          body = (await feedBody(env, sources)) || '{"sources":[]}';
        }
        return new Response(body, { headers: { ...cors, 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' } });
      }
      if (url.pathname === '/refresh' && req.method === 'POST') {
        const last = Number((await env.FEEDS.get('lastRefresh')) || 0);
        if (Date.now() - last < REFRESH_GAP) return json({ ok: true, skipped: true }, 200, cors);
        await env.FEEDS.put('lastRefresh', String(Date.now()));
        const done = await refreshNext(env, await loadSources(env));
        return json({ ok: true, refreshed: done }, 200, cors);
      }
      // Relay for Europe PMC (full text of open-access papers), in case the browser can't reach it
      // directly. Only its search and full-text XML paths are allowed, so this isn't an open proxy.
      if (url.pathname === '/epmc' && req.method === 'GET') {
        const path = url.searchParams.get('path') || '';
        if (!/^(search\?[^#]*|PMC\d{4,10}\/fullTextXML)$/.test(path)) return json({ error: 'not allowed' }, 400, cors);
        const r = await fetch('https://www.ebi.ac.uk/europepmc/webservices/rest/' + path, { cf: { cacheTtl: 86400 } });
        return new Response(r.body, { status: r.status, headers: { ...cors, 'content-type': r.headers.get('content-type') || 'text/plain' } });
      }
      if (url.pathname === '/' || url.pathname === '/health') {
        return json({ ok: true, name: 'bonsai-feeds' }, 200, cors);
      }
      return json({ error: 'not found' }, 404, cors);
    } catch (e) {
      return json({ error: String(e && e.message || e) }, 500, cors);
    }
  },

  async scheduled(event, env, ctx) {
    ctx.waitUntil(loadSources(env).then((sources) => refreshNext(env, sources)));
  },
};

async function loadSources(env) {
  const res = await fetch(env.SOURCES_URL || SOURCES_URL, { cf: { cacheTtl: 300 } });
  if (!res.ok) throw new Error('sources.json: HTTP ' + res.status);
  const cfg = await res.json();
  return (cfg.sources || []).filter((s) => s.feed);
}

// The stored entries stitched together as text (no JSON.parse of the big item lists).
async function feedBody(env, sources) {
  const entries = await Promise.all(sources.map((s) => env.FEEDS.getWithMetadata('src:' + s.id)));
  const parts = [];
  entries.forEach((e, i) => {
    if (!e.value) return;
    parts.push('{"id":' + JSON.stringify(sources[i].id) + ',"meta":' + JSON.stringify(e.metadata || {}) + ',"items":' + e.value + '}');
  });
  if (!parts.length) return '';
  return '{"updatedAt":' + JSON.stringify(new Date().toISOString()) + ',"sources":[' + parts.join(',') + ']}';
}

// Refresh the source that has waited longest (never-fetched ones first).
async function refreshNext(env, sources) {
  if (!sources.length) return null;
  const listed = await env.FEEDS.list({ prefix: 'src:' });
  const seen = new Map(listed.keys.map((k) => [k.name.slice(4), (k.metadata && k.metadata.fetchedAt) || 0]));
  const next = sources.slice().sort((a, b) => (seen.get(a.id) || 0) - (seen.get(b.id) || 0))[0];
  await refreshOne(env, next);
  return next.id;
}

async function refreshOne(env, s) {
  const key = 'src:' + s.id;
  try {
    const all = await fetchOne(s);
    const open = s.hideLocked ? all.filter((it) => !isLocked(it)) : all;
    const kept = open.slice(0, PER_SOURCE);
    await env.FEEDS.put(key, JSON.stringify(kept), {
      metadata: { fetchedAt: Date.now(), ok: true, count: kept.length, hidden: all.length - open.length },
    });
  } catch (e) {
    // Keep the last good items; just record the failure.
    const old = await env.FEEDS.getWithMetadata(key);
    await env.FEEDS.put(key, old.value || '[]', {
      metadata: { ...(old.metadata || {}), fetchedAt: Date.now(), ok: false, error: String(e && e.message || e).slice(0, 160) },
    });
  }
}

async function fetchOne(source) {
  const r = await fetch(source.feed, {
    headers: {
      'user-agent': 'BonsaiFeeds/0.1 (personal feed reader; +https://github.com/atonioguy/bonsai)',
      'accept': 'application/rss+xml, application/atom+xml, application/xml;q=0.9, text/xml;q=0.9, */*;q=0.5',
    },
    signal: AbortSignal.timeout(FETCH_TIMEOUT),
    cf: { cacheTtl: 900 },
  });
  if (!r.ok) throw new Error('HTTP ' + r.status);
  const xml = await r.text();
  // Parse a few spare items so hidden (locked) posts can be replaced.
  const items = parseFeed(xml, source, source.hideLocked ? PER_SOURCE * 2 : PER_SOURCE);
  if (!items.length && !/<(rss|feed|rdf:RDF)\b/i.test(xml)) throw new Error('not a feed');
  return items;
}

function json(obj, status, headers) {
  return new Response(JSON.stringify(obj), { status, headers: { ...headers, 'content-type': 'application/json; charset=utf-8' } });
}
