// Builds worker/bonsai-feeds.js: parse.js + worker.js as ONE file, for pasting into the
// Cloudflare dashboard editor. Run after editing either file:  node worker/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const here = (f) => new URL(f, import.meta.url);

export function bundle() {
  const parse = readFileSync(here('./parse.js'), 'utf8')
    .replace(/^export (function|const|async function)/gm, '$1');
  const worker = readFileSync(here('./worker.js'), 'utf8')
    .replace(/^import .*?from '\.\/parse\.js';\n/m, '')
    .replace(/^export (async function|function)/gm, '$1');
  return '// GENERATED by worker/build.mjs from parse.js + worker.js. Do not edit by hand.\n'
    + '// Paste this whole file into the Cloudflare dashboard editor (see worker/README.md).\n\n'
    + '// ===== parse.js =====\n' + parse
    + '\n// ===== worker.js =====\n' + worker;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(here('./bonsai-feeds.js'), bundle());
  console.log('wrote worker/bonsai-feeds.js');
}
